name: Basic Python Workflow

on:
  push:
    branches: [ main ]  # Change 'main' to your default branch if it's different
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies to run on the latest version of Ubuntu provided by GitHub-hosted runners

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Display Python version
      run: python -m pip --version

    - name: Execute Python script
      run: python hello.py
