name: Integration

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]
  workflow_dispatch:

jobs:
  configure_aws:
    runs-on: ubuntu-latest
    environment: production  # Specify the environment where your variables are configured
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Assuming this is stored as a secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Assuming this is stored as a secret
          aws-region: ${{ env.AWS_REGION }}  # Accessing environment variable correctly

  build_images_and_push:
    runs-on: ubuntu-latest
    environment: production  # Specify the same environment to ensure consistency
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        run: |
          echo "Building Docker images..."
          # Additional Docker commands here

  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes..."
          # Your Kubernetes deployment commands
