name: Python Application Workflow

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # Specifies that the job should run on the latest Ubuntu runner provided by GitHub

    steps:
    - name: Check out repository
      uses: actions/checkout@v2 # Uses a pre-built action to check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specifies the Python version to set up

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assumes you have a requirements.txt file at the root of your repository

    - name: Run a simple script
      run: |
        python my_script.py # Assumes you have a Python script named my_script.py at the root of your repository
